/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package student;


import java.util.ArrayList;
import preprocessing.Preprocessor;

/**
 *
 * @author welcome
 */
public class Student_Chat_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Student_Chat
     */
    public Student_Chat_Frame() {
        super(Student_ERP_No_Frame.student_name+" Chat Frame");
        initComponents();
        jTextArea1.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ask Question");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(21, 6, 106, 43);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jPanel1.add(jTextField1);
        jTextField1.setBounds(145, 6, 496, 43);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 204));
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(145, 67, 151, 43);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 138, 650, 621);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 204));
        jButton2.setText("Clear");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(366, 67, 148, 43);
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 0, 0);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/student/wood.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 680, 930);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 670, 920);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        String org_ques=jTextField1.getText();
        String preprocess_que=new Preprocessor().textProcessing(org_ques);
        
        ArrayList preprocessed_question_list=new ArrayList();
//        System.out.println(preprocess_que);
        
        System.out.println("\n\n----------------------------------------------------------------------Original list--------------------------------------------------------------------");
        
        ArrayList questionlist=new Questions_Answer_Fetcher().getQuestion("Student");
          for (int i = 0; i < questionlist.size(); i++)
        {
            ArrayList row=(ArrayList)questionlist.get(i);
            System.out.println(row);
        }
          
        for (int i = 0; i < questionlist.size(); i++) 
        {
            ArrayList row=(ArrayList)questionlist.get(i);
            String que=(String)row.get(0);
            String preprocess_que1=new Preprocessor().textProcessing(que);
            ArrayList temp=new ArrayList();
            temp.add(preprocess_que1);
            temp.add(row.get(1));
            preprocessed_question_list.add(temp);
            //System.out.println("preprocess_ans:  "+preprocess_ans);
        }
      
         System.out.println("\n\n----------------------------------------------------------------------preprocess list--------------------------------------------------------------------");
         for (int i = 0; i < preprocessed_question_list.size(); i++)
        {
            ArrayList row=(ArrayList)preprocessed_question_list.get(i);
            System.out.println(row);
        }
         
         
         
      ArrayList new_que_ans_score_list=new Check_Question_Equality().check_Question_Equality(preprocess_que, preprocessed_question_list);
      
        System.out.println("\n\n----------------------------------------------------------------------new_que_ans_score_list list--------------------------------------------------------------------");
        for (int i = 0; i < new_que_ans_score_list.size(); i++)
        {
            ArrayList row=(ArrayList)new_que_ans_score_list.get(i);
            System.out.println(row);
        }
        
        System.out.println("\n\n--------------------------------------------------------------Sorted List-----------------------------------------------------------------------------------------------");
        ArrayList sorted_list=new Sort().getSortedList(new_que_ans_score_list);
        for (int i = 0; i < sorted_list.size(); i++)
        {
            ArrayList row=(ArrayList)sorted_list.get(i);
            System.out.println(row);
        }
         System.out.println("Preprocessed given query is: "+preprocess_que);
        System.out.println("\n\n---------------------------------------------------------Top 2 Score-----------------------------------------------------------------------------------------------------------");
        
        
        for (int i = 0; i <2; i++)
        {
            ArrayList row=(ArrayList)sorted_list.get(i);
                System.out.println(row);
            
        }
        
        String orginal_Answer="";
       orginal_Answer=jTextArea1.getText();
        String answer="";
        for (int i = 0; i <2; i++)
        {
            
            for (int j = i+1; j < 2; j++) 
            {
                ArrayList row1=(ArrayList)sorted_list.get(i);
                double scr1=(double)row1.get(2);
                
                ArrayList row2=(ArrayList)sorted_list.get(j);
                double scr2=(double)row2.get(2);
                
                
                if(scr1!=scr2)
                {
                    String str=(String)row1.get(1);
                    answer=answer+str;
                }
                else
                {
                    String str1=(String)row1.get(1);
                     String str2=(String)row2.get(1);
                     
                    answer=answer+str1+"\n OR \n"+str2+"\n Please Contact Admin";
                }
            }
         //   str+"Parent"+" : "+question+ "?"+"\nChatbot : "+answer+".\n";
        }
            orginal_Answer=orginal_Answer+Student_ERP_No_Frame.student_name+" : "+org_ques+" \n SmartMate Bot : "+answer+". \n-----------------------------------------------------------------------------------------------------------------------------------\n";
            jTextArea1.setText(orginal_Answer);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextField1.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student_Chat_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student_Chat_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student_Chat_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student_Chat_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student_Chat_Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
